import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SupabaseProvider from "@/providers/SupabaseProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import Content from "@/components/Content";
import { MyUserContextProvider } from "@/hooks/useUser";
import { Toaster } from "sonner";
import ConfettiProvider from "@/providers/ConfettiProvider";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider>
          <SupabaseProvider>
            <MyUserContextProvider>
              <Sidebar className="p-8">
                <Content>
                  {children}
                  <Toaster />
                  <ConfettiProvider />
                </Content>
              </Sidebar>
            </MyUserContextProvider>
          </SupabaseProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
